# Generated by Django 5.0.2 on 2024-03-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grupos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grupo", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="noticias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=250)),
                ("fecha", models.DateField(auto_now=True)),
                ("contenido", models.CharField(max_length=3000)),
                ("imagen", models.CharField(max_length=250)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="app.grupos"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="comentarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                ("comentario", models.CharField(max_length=3000)),
                ("fecha", models.DateField(auto_now=True)),
                ("visible", models.BooleanField()),
                (
                    "noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="app.noticias"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                ("usuario", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("estado", models.CharField(max_length=50)),
                ("nivel", models.CharField(max_length=50)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.grupos"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="noticias",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="app.usuarios"
            ),
        ),
    ]
