# Generated by Django 5.0.2 on 2024-05-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_usuarios_grupo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticias",
            name="imagen",
            field=models.ImageField(null=True, upload_to="imagenes"),
        ),
    ]
