# Generated by Django 5.0.2 on 2024-06-07 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_noticias_subtitulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentarios",
            name="noticia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.noticias"
            ),
        ),
        migrations.AlterField(
            model_name="comentarios",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
